# Site settings
title: Zhiqi Lee's blog
description: A blog about Zhiqi Lee
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Zhiqi Lee
user_description: 明明什么都没干就已经2023了，明明太惨了<br />将就看吧，不会写html<br />
<img alt="平沙岛" src="{{ "/assets/img/平沙岛.png" | prepend: site.baseurl }}" />
# user_title: 娱乐空间
#email: anon@anon.com
#twitter_username: lorem_ipsum
github_username:  Zhiqilee
#gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
