# Site settings
title: Zhiqi Lee's blog
description: A blog about Zhiqi Lee
#baseurl: "/blog" # the subpath of your site, e.g. /blog
#url: "https://zhiqilee.github.io/" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Zhiqi Lee
user_description: 风乍起<br />合当奋意向此生
# user_title: 娱乐空间
#email: anon@anon.com
#twitter_username: lorem_ipsum
github_username:  Zhiqilee
#gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
